stages:
  - kill
  - build
  - deploy

job kill_old:
  stage: kill
  script: 
    - ssh root@back-1 'p=$(docker ps | grep pds-server | cut -d" " -f1);docker kill $p || exit 0 ;'
    - ssh root@back-2 'p=$(docker ps | grep pds-server | cut -d" " -f1);docker kill $p || exit 0 ;'

job build_new:
  stage: build
  script: 
    - ssh root@back-1 'docker build -t pds-server .'
    - ssh root@back-2 'docker build -t pds-server .'

job deploy_new:
  stage: deploy
  script: 
    - ssh root@back-1 'docker run -d -p 80:80 pds-server'
    - ssh root@back-2 'docker run -d -p 80:80 pds-server'
