stages:
  - kill
  - build
  - deploy

job kill_old:
  stage: kill
  script: p=$(docker ps | grep pds-server | cut -d" " -f1);docker kill $p ;

job build_new:
  stage: build
  script: docker build -t pds-server .

job deploy_new:
  stage: deploy
  script: docker run -d -p 80:80 pds-server
